export const MODULES = [
  { id: "humeur",           name: "Humeur du jour",        description: "Prenez la température en temps réel — chaque participant vote sur son état d'esprit.", href: "/toolbox/humeur",          emoji: "😊" },
  { id: "roti",             name: "ROTI",                  description: "Évaluez le retour sur temps investi d'une réunion en 30 secondes.",                       href: "/toolbox/roti",        emoji: "⭐" },
  { id: "retrospective",    name: "Rétrospective santé",   description: "Bilan d'équipe sur 9 critères : engagement, communication, clarté des rôles…",            href: "/toolbox/health-radar",             emoji: "🩺" },
  { id: "speed-retro",      name: "Speed Retro",           description: "Rétrospective rapide en mode post-its : ce qui va bien, ce qui bloque, les actions.",      href: "/toolbox/speed-retro",       emoji: "⚡" },
  { id: "kudo-cards",       name: "Kudo Cards",            description: "Envoyez des cartes de reconnaissance révélées en direct lors de votre session.",           href: "/reunion-maker/kudo-cards",  emoji: "🏆" },
  { id: "abcde",            name: "Atelier ABCDE",         description: "Facilitez une prise de décision collective en 5 étapes avec vote et synthèse IA.",         href: "/reunion-maker/abcde",       emoji: "🎯" },
  { id: "boussole",         name: "Boussole",              description: "Alignez votre équipe sur des valeurs et des principes communs.",                           href: "/boussole",                  emoji: "🧭" },
  { id: "icebreaker",       name: "Icebreaker",            description: "Questions fun pour briser la glace en début de réunion ou d'atelier.",                     href: "/icebreaker",                emoji: "🧊" },
  { id: "anecdotes",        name: "Anecdotes",             description: "Devinez qui a vécu quelle anecdote — idéal pour mieux se connaître en équipe.",           href: "/toolbox/anecdotes",       emoji: "📖" },
  { id: "draw",             name: "Draw It",               description: "Dessinez un mot pendant que vos collègues devinent — créativité et fous rires garantis.", href: "/toolbox/draw",            emoji: "🎨" },
  { id: "chaine",           name: "Chaîne de mots",        description: "Jeu d'association de mots en tour par tour avec vote sur la surprise du mot suivant.",     href: "/toolbox/chaine",          emoji: "🔗" },
  { id: "undercover",       name: "Undercover",            description: "Jeu de rôle : chaque joueur décrit son mot en secret, trouvez l'imposteur.",               href: "/toolbox/undercover",      emoji: "🕵️" },
  { id: "tribu",            name: "Tribu",                 description: "Découvrez à quelle tribu appartient chaque membre selon ses préférences et réflexes.",    href: "/toolbox/tribu",           emoji: "🏕️" },
  { id: "tvml",             name: "Tout vrai mon lapin",   description: "Vrai ou faux ? Des anecdotes vraies ou inventées sur vos collègues à deviner.",            href: "/toolbox/tvml",            emoji: "🎭" },
  { id: "reunion-preparer", name: "Préparer une réunion",  description: "Générez un ordre du jour structuré pour votre prochaine réunion grâce à l'IA.",           href: "/reunion-maker/preparer",    emoji: "📋" },
  { id: "feedback",         name: "Feedback structuré",    description: "Rédigez un feedback constructif, positif ou correctif grâce à l'IA.",                     href: "/feedback",                  emoji: "💬" },
  { id: "recruitment",      name: "Recrutement",           description: "Générez des fiches de poste et des questions d'entretien grâce à l'IA.",                  href: "/recruitment",               emoji: "👥" },
  { id: "coach",            name: "Coach 1:1",             description: "Suivez vos collaborateurs, planifiez vos entretiens individuels et gérez leurs objectifs.", href: "/coach",                    emoji: "🤝" },
  { id: "okr",              name: "OKR",                   description: "Définissez et suivez les objectifs et résultats clés de votre équipe.",                    href: "/coach/okr",                 emoji: "🎯" },
  { id: "academie",         name: "Académie (Quiz)",       description: "Formez-vous sur les compétences managériales avec des quiz et gagnez des badges.",         href: "/academie",                  emoji: "🎓" },
];
